# The landing/info page where you can download the MITM CA to your device
info_host = "free.news"
# Use Cloudflare DNS
upstream_dns = "1.1.1.1:53"

[[host]]
name = "example.com"
# Defaults: 
# from_google_cache = false
#   This option will ignore all other header based options
# social_referer = true
# googlebot_ua = true
# googlebot_ip = true
# disable_cookie = true
# disable_js = true
# inject_html = ""
