# The landing/info page where u can download the MITM CA to your device
info_host = "free.news"

[[host]]
name = "example.com"
# Defaults: 
# social_referer = true
# googlebot_ua = true
# googlebot_ip = true
# disble_cookies = true
# inject_html = ""

