# The landing/info page where u can download the MITM CA to your device
info_host = "free.news"

[[host]]
name = "ft.com"
# Defaults: 
# social_referer = true
# googlebot_ua = true
# googlebot_ip = true
# disble_cookies = true
# inject_html = ""

[[host]]
name = "theguardian.com"

[[host]]
name = "wsj.com"

[[host]]
name = "nytimes.com"

[[host]]
name = "telegraph.co.uk"

[[host]]
name = "bloomberg.com"
