# The landing/info page where u can download the MITM CA to your device
info_host = "free.news"
# Use Cloudflare DNS
upstream_dns = "1.1.1.1:53"

#Use AdGuard DNS
#upstream_dns = "94.140.14.14:53"

[[host]]
name = "example.com"
# Defaults: 
# social_referer = true
# googlebot_ua = true
# googlebot_ip = true
# disble_cookies = true
# inject_html = ""

